# test with : hello world docker action.
# test v4

on:
  push:
name: action
jobs:
  hello-world:
    name: Un job para saludar
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v3
      - name: Step Hola Mundo
        id: hello
        uses: sergioanino/hello-world-docker-action@v4
        with:
          who-to-greet: "Nino"
      - name: Usar el output
        run: echo "La fecha fue ${{ steps.hello.outputs.time }}"
