# test with : hello world docker action.
# test v5

on:
  push:
name: action
jobs:
  hello-world:
    name: Un job para saludar
    runs-on: ubuntu-latest
    steps:
      - name: Step Hola Mundo
        id: hello
        uses: sergioanino/hello-world-docker-action@v3
        with:
          who-to-greet: "sergioanino"
      - name: Usar el output
        run: echo "La fecha fue ${{ steps.hello.outputs.time }}"
